### ISSUE TITLE
Apply design feedback

### ISSUE THREAD

**Issue by pinkishincoloragain** [bsonCrew/QCA_Client#10]
- [x]  레드컬러를 주 컬러로 여러 부분에 적용 - 아이콘, 글 등 적용. (블랙을 베이스로)
- [x]  검색창 호버 레드
- [ ]  메인페이지 좀 더 디자인적으로꾸미기. 1번처럼 컬러를 좀더 적극 활용
- [x]  웨이브가 메인 그래픽이면 전체적으로 둥근 느낌을 주는 UI
- [x]  잘했어요 위험해요 카드는 버튼 기능이 아니면 좀 더 작아져도될듯
- [x]  수치가 중요하므로 수치를 부각시키는 디자인이 필요함
- [x]  총점 / 개선4가지 중 더 중요한걸 더 부각시켜야 함
- [ ]  메인 페이지에서 그라데이션을 사용했으므로 그래프에도 같이 그라데이션 적용
- [ ]  아이콘 더 예쁜 걸로
- [x]  컬러 뽑은거 컬러풀한 건 좋으나 그래프에 쓰기 눈이 아픔
- [x]  사이드바도 카테고리별로 묶어서 아이콘으로 나타내면 좋음.

@SeongukBaek 추가 디자인 사항 있으면 보안 부탁드립니다..

**Comment by SeongukBaek** [comment]
좋은 피드백이네요 ... 진행하시면 될 것 같습니다
