### ISSUE TITLE
Create landing page

### ISSUE THREAD

**Issue by pinkishincoloragain** [bsonCrew/QCA_Client#4]
create landing page including search bar

**Comment by pinkishincoloragain** [comment]
Created prototype of landing page.
Added tailwind css and react-spring for animation

@SeongukBaek UI 컨펌 부탁드립니다..

<img width="1680" alt="Screen Shot 2022-08-09 at 2 29 59" src="https://user-images.githubusercontent.com/39547381/183477995-14bf71ca-6b59-43c2-a656-3d1e545420e4.png">

**Comment by SeongukBaek** [comment]
명빈. UI 확인했습니다.
디자인이 괜찮군요.
오늘이나 내일 중으로 서버 배포해서 ip 보내드리겠습니다.
아 그리고, 노션이나 어디든 이슈나 과정들 기록해두시면 좋을 것 같네요.
그럼 이만.
